export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_RESET = 'AUTH_RESET';

export const CHECK_FAVORITES = 'CHECK_FAVORITES';
export const ADD_FAVROITE = 'ADD_FAVROITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const SET_ACTIVE_ROUTINE = 'SET_ACTIVE_ROUTINE';

export const START_SEARCH = 'START_SEARCH';
export const SET_EXERCISES = 'SET_EXERCISES';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const SET_WORKOUT_FORM_DATA = 'SET_WORKOUT_FORM_DATA';
export const SET_ENTIRE_WORKOUT_FORM = 'SET_ENTIRE_WORKOUT_FORM';
export const CLEAR_WORKOUT_FORM_DATA = 'CLEAR_WORKOUT_FORM_DATA';
export const RESET_WORKOUT_STORE = 'RESET_WORKOUT_STORE';
export const SET_FIREBASE_ID = 'SET_FIREBASE_ID';

export const SET_ROUTINES = 'SET_ROUTINES';
export const SET_WORKOUTS = 'SET_WORKOUTS';
export const SET_RECORDED_WORKOUTS = 'SET_RECORDED_WORKOUTS';
